name: Build-Ubuntu

on:
  workflow_call:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest
    steps:
      # install python on compute
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # install third-party libs
      - name: Install Testing and Formatting Libs
        run: |
          pip install black
          pip install pytest
          pip install pytest-cov
          echo Installed black, pytest and pytest-cov libs...