name: Protect Python PR

on:
  pull_request:
    branches: ["main"]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-latest
    uses: jl1608/GHActions_Python/.github/workflows/build-ubuntu.yaml@v1
    steps:
      - name: Check Formatting With Black
        run: black --check ./

      - name: Set status check
        id: status-check
        run: echo "::set-output name=status::$(black --check ./ && echo 'pass' || echo 'fail')"

      - name: Report status (check Fail)
        if: ${{ needs.status-check.outputs.status == 'fail' }}
        run: echo "Black formatting check failed. Please format your code using Black."

      - name: Report status (check Pass)
        if: ${{ needs.status-check.outputs.status == 'pass' }}
        run: echo "Black formatting check passed."

  test:
    runs-on: ubuntu-latest
    uses: .github/workflows/build-ubuntu.yaml
    steps:
      - name: Check all test cases are passing
        run: pytest ./pytest_example.py
    
      - name: Set status check
        id: status-check
        run: echo "::set-output name=status::$(pytest ./pytest_example.py && echo 'pass' || echo 'fail')"

      - name: Report status (check Fail)
        if: ${{ needs.status-check.outputs.status == 'fail' }}
        run: echo "Pytest formatting check failed. Please ensure all test cases are passing."

      - name: Report status (check Pass)
        if: ${{ needs.status-check.outputs.status == 'pass' }}
        run: echo "Pytest check passed."
